#!/bin/sh

clean_and_die() {
  cd $orig_dir
  rm -rf tmp
  exit $1
}

orig_dir=$(pwd)
mkdir tmp

cp -rvf book.ltx appendices/* chapters/* bibliographies/* images/* tmp/
cd tmp

xelatex book.ltx || clean_and_die 1
bibtex book
xelatex book.ltx && xelatex book.ltx

cp book.pdf ..
clean_and_die 0
